### ISSUE TITLE
Unable to make bot in mattermost 

### ISSUE THREAD

**Issue by cyanide1323** [mattermost/mattermost-bot-sample-golang#24]
./bin/platform team create --name botsample --display_name "Sample Bot playground" --email "admin@example.com"

output : botsample --display_name "Sample Bot playground" --email "admin@example.com" --debug
-bash: ./bin/platform: No such file or directory

running the latest version of mattermost server on localhost:8605. Followed the Readmd file with no luck. One youtube video shows mattermost/platform repo which I was unable to find. Can someone guide.

**Comment by hanzei** [comment]
Hey @cyanide1323,

Thanks for the report. We updated the readme to address your confusion. Would you please try a second time?

**Comment by cyanide1323** [comment]
Hi,

I'm running this command : ./bin/mattermost team create --name botsample
--display_name "Sample Bot playground" --email "admin@example.com"
inside my mattermost-bot-sample-golang repo  while mattermost-server and
web-client running parallelly on another terminal. It is still showing file
not found. Can you please tell if anything else is required to do so as to
make it run. Attached screenshot of my terminal.

Thanks and Regards,
Himanshu Tomar

**Comment by hanzei** [comment]
Hey @cyanide1323,

If you are using a development environment, you need to run:
`go run ./cmd/mattermost/ team create --name botsample --display_name "Sample Bot playground" --email "admin@example.com"`
inside you mattermost server directory.

**Comment by cyanide1323** [comment]
Hi,

Thanks for the help it worked. I appreciate your efforts to help me out.

Thanks and regards,
Himanshu Tomar
